version: '3.9'

services:
  app_fastapi:
    build:
      context: ./app_fastapi
      dockerfile: Dockerfile
    volumes:
      - shared_data:/shared_data

  app_flask:
    build:
      context: ./app_flask
      dockerfile: Dockerfile
    volumes:
      - shared_data:/shared_data

  app_streamlit:
    build:
      context: ./app_streamlit
      dockerfile: Dockerfile
    volumes:
      - shared_data:/shared_data

#  main:
#    build:
#      context: .
#      dockerfile: Dockerfile_main
#    depends_on:
#      - app1
#      - app2
#      - app3

volumes:
  shared_data:
    external: true