version: '3.9'

services:
  app_fastapi:
    build:
      context: ./app_fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  app_flask:
    build:
      context: ./app_flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  app_streamlit:
    build:
      context: ./app_streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"

volumes:
  shared_data:
    external: true